__author__ = 'Andrew Boughton and the A2 Hack for Change team'
# Contains lookup information for converting time series information using strange CDC field names into
#  standardizd, machine readable formats for date, location, etc

# Months are 0-based for compatibility with timedelta
month_lookup = {'January': 0, 'February': 1, 'March': 2, 'April': 3, 'May': 4,
                'June': 5, 'July': 6, 'August': 7, 'September': 8, 'October': 9,
                'November': 10, 'December': 11}


# Abbreviations sourced from USPS:
#  https://www.usps.com/send/official-abbreviations.htm
geography = {'UNITED STATES': 'USA',
             'NEW ENGLAND': 'REGION New England',
             'Conn.': 'CT',
             'Maine': 'ME',
             'Mass.': 'MA',
             'N.H.': 'NH',
             'R.I.':'RI',
             'Vt.': 'VT',
             'MID. ATLANTIC': 'REGION Mid-atlantic',
             'N.J.': 'NJ',
             'N.Y. (Upstate)': 'NY (upstate)',
             'N.Y. City': 'NY (City)',
             'Pa.': 'PA',
             'E.N. CENTRAL': 'REGION Northeast-central',
             'Ill.': 'IL',
             'Ind.': 'IN',
             'Mich.': 'MI',
             'Ohio': 'OH',
             'Wis.': 'WI',
             'W.N. CENTRAL': 'REGION Northwest-central',
             'Iowa': 'IA',
             'Kans.': 'KS',
             'Minn.': 'MN',
             'Mo.': 'MO',
             'Nebr.': 'NE',
             'N. Dak.': 'ND',
             'S. Dak.': 'SD',
             'S. ATLANTIC': 'REGION South-atlantic',
             'Del.': 'DE',
             'D.C.': 'DC',
             'Fla.': 'FL',
             'Ga.': 'GA',
             'Md.': 'MD',
             'N.C.': 'NC',
             'S.C.': 'SC',
             'Va.': 'VA',
             'W. Va.': 'WV',
             'E.S. CENTRAL': 'REGION Southeast-central',
             'Ala.': 'AL',
             'Ky.': 'KY',
             'Miss.': 'MS',
             'Tenn.': 'TN',
             'W.S. CENTRAL': 'REGION Southwest-central',
             'Ark.': 'AK',
             'La.': 'LA',
             'Okla.': 'OK',
             'Tex.': 'TX',
             'MOUNTAIN': 'REGION Mountain',
             'Ariz.': 'AZ',
             'Colo.': 'CO',
             'Idaho': 'ID',
             'Mont.': 'MT',
             'Nev.': 'NV',
             'N. Mex.': 'NM',
             'Utah': 'UT',
             'Wyo.': 'WY',
             'PACIFIC': 'REGION Pacific',
             'Alaska': 'AK',
             'Calif.': 'CA',
             'Hawaii': 'HI',
             'Oreg.': 'OR',
             'Wash.': 'WA',
             'Amer. Samoa': 'AS',
             'C.N.M.I.': 'MP',
             'Guam': 'GU',
             'P.R.': 'PR',
             'V.I.': 'VI'}