__author__ = 'Andrew Boughton and the A2 Hack for Change team'
# Contains lookup information for converting time series information using strange CDC field names into
#  standardizd, machine readable formats for date, location, etc

# Months are 0-based for compatibility with timedelta
month_lookup = {'January': 0,
                'February': 1,
                'March': 2,
                'April': 3,
                'May': 4,
                'June': 5,
                'July': 6,
                'August': 7,
                'September': 8,
                'October': 9,
                'November': 10,
                'December': 11}


# Abbreviations sourced from USPS:
#  https://www.usps.com/send/official-abbreviations.htm
geography = {'UNITED STATES': 'USA',
             'NEW ENGLAND': 'REGION New England',
             'Conn.': 'CT',
             'Maine': 'ME',
             'Mass.': 'MA',
             'N.H.': 'NH',
             'R.I.':'RI',
             'Vt.': 'VT',
             'MID. ATLANTIC': 'REGION Mid-atlantic',
             'N.J.': 'NJ',
             'N.Y. (Upstate)': 'NY (upstate)',
             'Upstate N.Y.': 'NY (upstate)',
             'N.Y. City': 'NY (City)',
             'Pa.': 'PA',
             'E.N. CENTRAL': 'REGION Northeast-central',
             'Ill.': 'IL',
             'Ind.': 'IN',
             'Mich.': 'MI',
             'Ohio': 'OH',
             'Wis.': 'WI',
             'W.N. CENTRAL': 'REGION Northwest-central',
             'Iowa': 'IA',
             'Kans.': 'KS',
             'Minn.': 'MN',
             'Mo.': 'MO',
             'Nebr.': 'NE',
             'N. Dak.': 'ND',
             'S. Dak.': 'SD',
             'S. ATLANTIC': 'REGION South-atlantic',
             'Del.': 'DE',
             'D.C.': 'DC',
             'Fla.': 'FL',
             'Ga.': 'GA',
             'Md.': 'MD',
             'N.C.': 'NC',
             'S.C.': 'SC',
             'Va.': 'VA',
             'W. Va.': 'WV',
             'E.S. CENTRAL': 'REGION Southeast-central',
             'Ala.': 'AL',
             'Ky.': 'KY',
             'Miss.': 'MS',
             'Tenn.': 'TN',
             'W.S. CENTRAL': 'REGION Southwest-central',
             'Ark.': 'AK',
             'La.': 'LA',
             'Okla.': 'OK',
             'Tex.': 'TX',
             'MOUNTAIN': 'REGION Mountain',
             'Ariz.': 'AZ',
             'Colo.': 'CO',
             'Idaho': 'ID',
             'Mont.': 'MT',
             'Nev.': 'NV',
             'N. Mex.': 'NM',
             'Utah': 'UT',
             'Wyo.': 'WY',
             'PACIFIC': 'REGION Pacific',
             'Alaska': 'AK',
             'Calif.': 'CA',
             'Hawaii': 'HI',
             'Oreg.': 'OR',
             'Wash.': 'WA',
             'Amer. Samoa': 'AS',
             'C.N.M.I.': 'MP',
             'Guam': 'GU',
             'P.R.': 'PR',
             'V.I.': 'VI'}

# These are the unique field (column) names in all variants of table 2, 2000-2013. Encountered some issues with
#  malformed tables from 1996-1999 (specifically those that said "this table wasn't published in this time period")-
#  hence this list may not include every fieldname when examining the very oldest tab files

# This needs to be converted to a dictionary so that the column name can be mapped to metadata, like
#    (diseasename, time period, type of statistic)
# That way we can track specific diseases in the database
column_metadata = ['AIDS \xa7 cummulative for 1999',
     'AIDS \xa7 cummulative for 2000',
     'AIDS \xa7 cummulative for 2001',
     'AIDS \xa7 cummulative for 2002',
     'AIDS \xa7 cummulative for 2003',
     'AIDS \xa7 cummulative for 2004',
     'AIDS \xa7 cummulative for 2005',
     'Chlamydia trachomatis infection cummulative for 2009',
     'Chlamydia trachomatis infection cummulative for 2010',
     'Chlamydia trachomatis infection cummulative for 2011',
     'Chlamydia trachomatis infection cummulative for 2012',
     'Chlamydia trachomatis infection cummulative for 2013',
     'Chlamydia trachomatis infection current week',
     'Chlamydia trachomatis infection previous 52 weeks maximum ',
     'Chlamydia trachomatis infection previous 52 weeks median ',
     'Chlamydia\x86 cummulative for 1999',
     'Chlamydia\x86 cummulative for 2000',
     'Chlamydia\x86 cummulative for 2001',
     'Chlamydia\x86 cummulative for 2002',
     'Chlamydia\x86 cummulative for 2003',
     'Chlamydia\x86 cummulative for 2004',
     'Chlamydia\x86 cummulative for 2005',
     'Chlamydia\x86 cummulative for 2006',
     'Chlamydia\x86 cummulative for 2007',
     'Chlamydia\x86 cummulative for 2008',
     'Chlamydia\x86 cummulative for 2009',
     'Chlamydia\x86 current week',
     'Chlamydia\x86 previous 52 weeks maximum ',
     'Chlamydia\x86 previous 52 weeks median ',
     'Coccidioidomycosis cummulative for 2002',
     'Coccidioidomycosis cummulative for 2003',
     'Coccidioidomycosis cummulative for 2004',
     'Coccidioidomycosis cummulative for 2005',
     'Coccidioidomycosis cummulative for 2006',
     'Coccidioidomycosis cummulative for 2007',
     'Coccidioidomycosis cummulative for 2008',
     'Coccidioidomycosis cummulative for 2009',
     'Coccidioidomycosis cummulative for 2010',
     'Coccidioidomycosis cummulative for 2011',
     'Coccidioidomycosis cummulative for 2012',
     'Coccidioidomycosis cummulative for 2013',
     'Coccidioidomycosis current week',
     'Coccidioidomycosis previous 52 weeks maximum ',
     'Coccidioidomycosis previous 52 weeks median ',
     'Cryptosporidiosis cummulative for 1999',
     'Cryptosporidiosis cummulative for 2000',
     'Cryptosporidiosis cummulative for 2001',
     'Cryptosporidiosis cummulative for 2002',
     'Cryptosporidiosis cummulative for 2003',
     'Cryptosporidiosis cummulative for 2004',
     'Cryptosporidiosis cummulative for 2005',
     'Cryptosporidiosis cummulative for 2006',
     'Cryptosporidiosis cummulative for 2007',
     'Cryptosporidiosis cummulative for 2008',
     'Cryptosporidiosis cummulative for 2009',
     'Cryptosporidiosis cummulative for 2010',
     'Cryptosporidiosis cummulative for 2011',
     'Cryptosporidiosis cummulative for 2012',
     'Cryptosporidiosis cummulative for 2013',
     'Cryptosporidiosis current week',
     'Cryptosporidiosis previous 52 weeks maximum ',
     'Cryptosporidiosis previous 52 weeks median ',
     'Dengue Virus Infection, Dengue Fever\x86 cummulative for 2009',
     'Dengue Virus Infection, Dengue Fever\x86 cummulative for 2010',
     'Dengue Virus Infection, Dengue Fever\x86 cummulative for 2011',
     'Dengue Virus Infection, Dengue Fever\x86 cummulative for 2012',
     'Dengue Virus Infection, Dengue Fever\x86 cummulative for 2013',
     'Dengue Virus Infection, Dengue Fever\x86 current week',
     'Dengue Virus Infection, Dengue Fever\x86 previous 52 weeks maximum ',
     'Dengue Virus Infection, Dengue Fever\x86 previous 52 weeks median ',
     'Dengue Virus Infection, Dengue Hemorrhagic Fever \xa7 cummulative for 2009',
     'Dengue Virus Infection, Dengue Hemorrhagic Fever \xa7 cummulative for 2010',
     'Dengue Virus Infection, Dengue Hemorrhagic Fever \xa7 cummulative for 2011',
     'Dengue Virus Infection, Dengue Hemorrhagic Fever \xa7 cummulative for 2012',
     'Dengue Virus Infection, Dengue Hemorrhagic Fever \xa7 cummulative for 2013',
     'Dengue Virus Infection, Dengue Hemorrhagic Fever \xa7 current week',
     'Dengue Virus Infection, Dengue Hemorrhagic Fever \xa7 previous 52 weeks maximum ',
     'Dengue Virus Infection, Dengue Hemorrhagic Fever \xa7 previous 52 weeks median ',
     'Ehrlichiosis/Anaplasmosis\x86, Anaplasma phagocytophilum cummulative for 2009',
     'Ehrlichiosis/Anaplasmosis\x86, Anaplasma phagocytophilum cummulative for 2010',
     'Ehrlichiosis/Anaplasmosis\x86, Anaplasma phagocytophilum cummulative for 2011',
     'Ehrlichiosis/Anaplasmosis\x86, Anaplasma phagocytophilum cummulative for 2012',
     'Ehrlichiosis/Anaplasmosis\x86, Anaplasma phagocytophilum cummulative for 2013',
     'Ehrlichiosis/Anaplasmosis\x86, Anaplasma phagocytophilum current week',
     'Ehrlichiosis/Anaplasmosis\x86, Anaplasma phagocytophilum previous 52 weeks maximum ',
     'Ehrlichiosis/Anaplasmosis\x86, Anaplasma phagocytophilum previous 52 weeks median ',
     'Ehrlichiosis/Anaplasmosis\x86, Ehrlichia chaffeensis cummulative for 2009',
     'Ehrlichiosis/Anaplasmosis\x86, Ehrlichia chaffeensis cummulative for 2010',
     'Ehrlichiosis/Anaplasmosis\x86, Ehrlichia chaffeensis cummulative for 2011',
     'Ehrlichiosis/Anaplasmosis\x86, Ehrlichia chaffeensis cummulative for 2012',
     'Ehrlichiosis/Anaplasmosis\x86, Ehrlichia chaffeensis cummulative for 2013',
     'Ehrlichiosis/Anaplasmosis\x86, Ehrlichia chaffeensis current week',
     'Ehrlichiosis/Anaplasmosis\x86, Ehrlichia chaffeensis previous 52 weeks maximum ',
     'Ehrlichiosis/Anaplasmosis\x86, Ehrlichia chaffeensis previous 52 weeks median ',
     'Ehrlichiosis/Anaplasmosis\x86, Undetermined cummulative for 2009',
     'Ehrlichiosis/Anaplasmosis\x86, Undetermined cummulative for 2010',
     'Ehrlichiosis/Anaplasmosis\x86, Undetermined cummulative for 2011',
     'Ehrlichiosis/Anaplasmosis\x86, Undetermined cummulative for 2012',
     'Ehrlichiosis/Anaplasmosis\x86, Undetermined cummulative for 2013',
     'Ehrlichiosis/Anaplasmosis\x86, Undetermined current week',
     'Ehrlichiosis/Anaplasmosis\x86, Undetermined previous 52 weeks maximum ',
     'Ehrlichiosis/Anaplasmosis\x86, Undetermined previous 52 weeks median ',
     'Encephalitis/Meningitis West Nile cummulative for 2002',
     'Encephalitis/Meningitis West Nile cummulative for 2003',
     'Encephalitis/Meningitis West Nile cummulative for 2004',
     'Escherichia coli O157:H7 NETSS cummulative for 1999',
     'Escherichia coli O157:H7 NETSS cummulative for 2000',
     'Escherichia coli O157:H7 NETSS cummulative for 2001',
     'Escherichia coli O157:H7 PHLIS cummulative for 1999',
     'Escherichia coli O157:H7 PHLIS cummulative for 2000',
     'Escherichia coli O157:H7 PHLIS cummulative for 2001',
     'Escherichia coli O157:H7 cummulative for 2001',
     'Escherichia coli O157:H7 cummulative for 2002',
     'Escherichia coli Shiga toxin positive, serogroup non-0157 cummulative for 2001',
     'Escherichia coli Shiga toxin positive, serogroup non-0157 cummulative for 2002',
     'Escherichia coli, Enterohemorrhagic, (EHEC), 0157:H7 cummulative for 2002',
     'Escherichia coli, Enterohemorrhagic, (EHEC), 0157:H7 cummulative for 2003',
     'Escherichia coli, Enterohemorrhagic, (EHEC), 0157:H7 cummulative for 2004',
     'Escherichia coli, Enterohemorrhagic, (EHEC), 0157:H7 cummulative for 2005',
     'Escherichia coli, Enterohemorrhagic, (EHEC), shiga toxin positive, not serogrouped cummulative for 2002',
     'Escherichia coli, Enterohemorrhagic, (EHEC), shiga toxin positive, not serogrouped cummulative for 2003',
     'Escherichia coli, Enterohemorrhagic, (EHEC), shiga toxin positive, not serogrouped cummulative for 2004',
     'Escherichia coli, Enterohemorrhagic, (EHEC), shiga toxin positive, not serogrouped cummulative for 2005',
     'Escherichia coli, Enterohemorrhagic, (EHEC), shiga toxin positive, serogroup non-0157 cummulative for 2002',
     'Escherichia coli, Enterohemorrhagic, (EHEC), shiga toxin positive, serogroup non-0157 cummulative for 2003',
     'Escherichia coli, Enterohemorrhagic, (EHEC), shiga toxin positive, serogroup non-0157 cummulative for 2004',
     'Escherichia coli, Enterohemorrhagic, (EHEC), shiga toxin positive, serogroup non-0157 cummulative for 2005',
     'Escherichia coli, Enterohemorrhagic, O157:H7 cummulative for 2001',
     'Escherichia coli, Enterohemorrhagic, O157:H7 cummulative for 2002',
     'Escherichia coli, Enterohemorrhagic, Shiga toxin positive, serogroup non-0157 cummulative for 2001',
     'Escherichia coli, Enterohemorrhagic, Shiga toxin positive, serogroup non-0157 cummulative for 2002',
     'Escherichia coli, Enterohemorrhagic, shiga toxin positive, not serogrouped cummulative for 2001',
     'Escherichia coli, Enterohemorrhagic, shiga toxin positive, not serogrouped cummulative for 2002',
     'Escherichia coli, shiga toxin positive, not serogrouped cummulative for 2001',
     'Escherichia coli, shiga toxin positive, not serogrouped cummulative for 2002',
     'Giardiasis cummulative for 2002',
     'Giardiasis cummulative for 2003',
     'Giardiasis cummulative for 2004',
     'Giardiasis cummulative for 2005',
     'Giardiasis cummulative for 2006',
     'Giardiasis cummulative for 2007',
     'Giardiasis cummulative for 2008',
     'Giardiasis cummulative for 2009',
     'Giardiasis cummulative for 2010',
     'Giardiasis cummulative for 2011',
     'Giardiasis cummulative for 2012',
     'Giardiasis cummulative for 2013',
     'Giardiasis current week',
     'Giardiasis previous 52 weeks maximum ',
     'Giardiasis previous 52 weeks median ',
     'Gonorrhea cummulative for 1999',
     'Gonorrhea cummulative for 2000',
     'Gonorrhea cummulative for 2001',
     'Gonorrhea cummulative for 2002',
     'Gonorrhea cummulative for 2003',
     'Gonorrhea cummulative for 2004',
     'Gonorrhea cummulative for 2005',
     'Gonorrhea cummulative for 2006',
     'Gonorrhea cummulative for 2007',
     'Gonorrhea cummulative for 2008',
     'Gonorrhea cummulative for 2009',
     'Gonorrhea cummulative for 2010',
     'Gonorrhea cummulative for 2011',
     'Gonorrhea cummulative for 2012',
     'Gonorrhea cummulative for 2013',
     'Gonorrhea current week',
     'Gonorrhea previous 52 weeks maximum ',
     'Gonorrhea previous 52 weeks median ',
     'Haemophilus influenzae, Invasive, Age < 5 years, Serotype B cummulative for 2001',
     'Haemophilus influenzae, Invasive, Age < 5 years, Serotype B cummulative for 2002',
     'Haemophilus influenzae, Invasive, Age < 5 years, Serotype B cummulative for 2003',
     'Haemophilus influenzae, Invasive, Age < 5 years, Serotype B cummulative for 2004',
     'Haemophilus influenzae, Invasive, Age < 5 years, Serotype B cummulative for 2005',
     'Haemophilus influenzae, Invasive, Age < 5 years, Unknown Serotype cummulative for 2001',
     'Haemophilus influenzae, Invasive, Age < 5 years, Unknown Serotype cummulative for 2002',
     'Haemophilus influenzae, Invasive, Age < 5 years, Unknown Serotype cummulative for 2003',
     'Haemophilus influenzae, Invasive, Age < 5 years, Unknown Serotype cummulative for 2004',
     'Haemophilus influenzae, Invasive, Age < 5 years, Unknown Serotype cummulative for 2005',
     'Haemophilus influenzae, Invasive, Age < 5 years, non-Serotype B cummulative for 2001',
     'Haemophilus influenzae, Invasive, Age < 5 years, non-Serotype B cummulative for 2002',
     'Haemophilus influenzae, Invasive, Age < 5 years, non-Serotype B cummulative for 2003',
     'Haemophilus influenzae, Invasive, Age < 5 years, non-Serotype B cummulative for 2004',
     'Haemophilus influenzae, Invasive, Age < 5 years, non-Serotype B cummulative for 2005',
     'Haemophilus influenzae, Invasive, All Ages, All serotypes cummulative for 2002',
     'Haemophilus influenzae, Invasive, All Ages, All serotypes cummulative for 2003',
     'Haemophilus influenzae, Invasive, All Ages, All serotypes cummulative for 2004',
     'Haemophilus influenzae, Invasive, All Ages, All serotypes cummulative for 2005',
     'Haemophilus influenzae, Invasive, All ages, All serotypes cummulative for 2001',
     'Haemophilus influenzae, Invasive, All ages, All serotypes cummulative for 2002',
     'Haemophilus influenzae, invasive, All ages, all serotypes cummulative for 2005',
     'Haemophilus influenzae, invasive, All ages, all serotypes cummulative for 2006',
     'Haemophilus influenzae, invasive, All ages, all serotypes current week',
     'Haemophilus influenzae, invasive, All ages, all serotypes previous 52 weeks maximum ',
     'Haemophilus influenzae, invasive, All ages, all serotypes previous 52 weeks median ',
     'Haemophilus influenzae, invasive, All ages, all serotypes \x86 cummulative for 2009',
     'Haemophilus influenzae, invasive, All ages, all serotypes \x86 cummulative for 2010',
     'Haemophilus influenzae, invasive, All ages, all serotypes \x86 cummulative for 2011',
     'Haemophilus influenzae, invasive, All ages, all serotypes \x86 cummulative for 2012',
     'Haemophilus influenzae, invasive, All ages, all serotypes \x86 cummulative for 2013',
     'Haemophilus influenzae, invasive, All ages, all serotypes \x86 current week',
     'Haemophilus influenzae, invasive, All ages, all serotypes \x86 previous 52 weeks maximum ',
     'Haemophilus influenzae, invasive, All ages, all serotypes \x86 previous 52 weeks median ',
     'Haemophilus influenzae, invasive, All ages, all serotypes\x86 cummulative for 2006',
     'Haemophilus influenzae, invasive, All ages, all serotypes\x86 cummulative for 2007',
     'Haemophilus influenzae, invasive, All ages, all serotypes\x86 cummulative for 2008',
     'Haemophilus influenzae, invasive, All ages, all serotypes\x86 cummulative for 2009',
     'Haemophilus influenzae, invasive, All ages, all serotypes\x86 current week',
     'Haemophilus influenzae, invasive, All ages, all serotypes\x86 previous 52 weeks maximum ',
     'Haemophilus influenzae, invasive, All ages, all serotypes\x86 previous 52 weeks median ',
     'Hepatitis (Viral Acute), Type A cummulative for 2002',
     'Hepatitis (Viral Acute), Type A cummulative for 2003',
     'Hepatitis (Viral Acute), Type A cummulative for 2004',
     'Hepatitis (Viral Acute), Type A cummulative for 2005',
     'Hepatitis (Viral Acute), Type A cummulative for 2006',
     'Hepatitis (Viral Acute), Type A cummulative for 2009',
     'Hepatitis (Viral Acute), Type A cummulative for 2010',
     'Hepatitis (Viral Acute), Type A cummulative for 2011',
     'Hepatitis (Viral Acute), Type A cummulative for 2012',
     'Hepatitis (Viral Acute), Type A cummulative for 2013',
     'Hepatitis (Viral Acute), Type A current week',
     'Hepatitis (Viral Acute), Type A previous 52 weeks maximum ',
     'Hepatitis (Viral Acute), Type A previous 52 weeks median ',
     'Hepatitis (Viral Acute), Type A\x86 cummulative for 2006',
     'Hepatitis (Viral Acute), Type A\x86 cummulative for 2007',
     'Hepatitis (Viral Acute), Type A\x86 cummulative for 2008',
     'Hepatitis (Viral Acute), Type A\x86 cummulative for 2009',
     'Hepatitis (Viral Acute), Type A\x86 current week',
     'Hepatitis (Viral Acute), Type A\x86 previous 52 weeks maximum ',
     'Hepatitis (Viral Acute), Type A\x86 previous 52 weeks median ',
     'Hepatitis (Viral Acute), Type B cummulative for 2005',
     'Hepatitis (Viral Acute), Type B cummulative for 2006',
     'Hepatitis (Viral Acute), Type B cummulative for 2009',
     'Hepatitis (Viral Acute), Type B cummulative for 2010',
     'Hepatitis (Viral Acute), Type B cummulative for 2011',
     'Hepatitis (Viral Acute), Type B cummulative for 2012',
     'Hepatitis (Viral Acute), Type B cummulative for 2013',
     'Hepatitis (Viral Acute), Type B current week',
     'Hepatitis (Viral Acute), Type B previous 52 weeks maximum ',
     'Hepatitis (Viral Acute), Type B previous 52 weeks median ',
     'Hepatitis (Viral Acute), Type B\x86 cummulative for 2006',
     'Hepatitis (Viral Acute), Type B\x86 cummulative for 2007',
     'Hepatitis (Viral Acute), Type B\x86 cummulative for 2008',
     'Hepatitis (Viral Acute), Type B\x86 cummulative for 2009',
     'Hepatitis (Viral Acute), Type B\x86 current week',
     'Hepatitis (Viral Acute), Type B\x86 previous 52 weeks maximum ',
     'Hepatitis (Viral Acute), Type B\x86 previous 52 weeks median ',
     'Hepatitis (Viral Acute), Type C cummulative for 2009',
     'Hepatitis (Viral Acute), Type C cummulative for 2010',
     'Hepatitis (Viral Acute), Type C cummulative for 2011',
     'Hepatitis (Viral Acute), Type C cummulative for 2012',
     'Hepatitis (Viral Acute), Type C cummulative for 2013',
     'Hepatitis (Viral Acute), Type C current week',
     'Hepatitis (Viral Acute), Type C previous 52 weeks maximum ',
     'Hepatitis (Viral Acute), Type C previous 52 weeks median ',
     'Hepatitis (Viral), Type A cummulative for 2001',
     'Hepatitis (Viral), Type A cummulative for 2002',
     'Hepatitis (Viral), Type B cummulative for 2001',
     'Hepatitis (Viral), Type B cummulative for 2002',
     'Hepatitis (Viral), Type C; Non-A, Non-B cummulative for 2001',
     'Hepatitis (Viral), Type C; Non-A, Non-B cummulative for 2002',
     'Hepatitis (Viral, Acute), Type A cummulative for 2004',
     'Hepatitis (Viral, Acute), Type A cummulative for 2005',
     'Hepatitis (Viral, Acute), Type B cummulative for 2002',
     'Hepatitis (Viral, Acute), Type B cummulative for 2003',
     'Hepatitis (Viral, Acute), Type B cummulative for 2004',
     'Hepatitis (Viral, Acute), Type B cummulative for 2005',
     'Hepatitis (Viral, Acute), Type C cummulative for 2003',
     'Hepatitis (Viral, Acute), Type C cummulative for 2004',
     'Hepatitis (Viral, Acute), Type C cummulative for 2005',
     'Hepatitis (Viral, Acute), Type c cummulative for 2002',
     'Hepatitis (Viral, Acute), Type c cummulative for 2003',
     'Hepatitis (Viral, Acute), Type c cummulative for 2004',
     'Hepatitis C/NA,NB cummulative for 1999',
     'Hepatitis C/NA,NB cummulative for 2000',
     'Hepatitis C/NA,NB cummulative for 2001',
     'Legionellosis cummulative for 1999',
     'Legionellosis cummulative for 2000',
     'Legionellosis cummulative for 2001',
     'Legionellosis cummulative for 2002',
     'Legionellosis cummulative for 2003',
     'Legionellosis cummulative for 2004',
     'Legionellosis cummulative for 2005',
     'Legionellosis cummulative for 2006',
     'Legionellosis cummulative for 2007',
     'Legionellosis cummulative for 2008',
     'Legionellosis cummulative for 2009',
     'Legionellosis cummulative for 2010',
     'Legionellosis cummulative for 2011',
     'Legionellosis cummulative for 2012',
     'Legionellosis cummulative for 2013',
     'Legionellosis current week',
     'Legionellosis previous 52 weeks maximum ',
     'Legionellosis previous 52 weeks median ',
     'Listeriosis cummulative for 1999',
     'Listeriosis cummulative for 2000',
     'Listeriosis cummulative for 2001',
     'Listeriosis cummulative for 2002',
     'Listeriosis cummulative for 2003',
     'Listeriosis cummulative for 2004',
     'Listeriosis cummulative for 2005',
     'Lyme Disease cummulative for 1999',
     'Lyme Disease cummulative for 2000',
     'Lyme Disease cummulative for 2001',
     'Lyme Disease cummulative for 2002',
     'Lyme Disease cummulative for 2003',
     'Lyme Disease cummulative for 2004',
     'Lyme Disease cummulative for 2005',
     'Lyme disease cummulative for 2005',
     'Lyme disease cummulative for 2006',
     'Lyme disease cummulative for 2007',
     'Lyme disease cummulative for 2008',
     'Lyme disease cummulative for 2009',
     'Lyme disease cummulative for 2010',
     'Lyme disease cummulative for 2011',
     'Lyme disease cummulative for 2012',
     'Lyme disease cummulative for 2013',
     'Lyme disease current week',
     'Lyme disease previous 52 weeks maximum ',
     'Lyme disease previous 52 weeks median ',
     'Malaria cummulative for 1999',
     'Malaria cummulative for 2000',
     'Malaria cummulative for 2001',
     'Malaria cummulative for 2002',
     'Malaria cummulative for 2003',
     'Malaria cummulative for 2004',
     'Malaria cummulative for 2005',
     'Malaria cummulative for 2006',
     'Malaria cummulative for 2007',
     'Malaria cummulative for 2008',
     'Malaria cummulative for 2009',
     'Malaria cummulative for 2010',
     'Malaria cummulative for 2011',
     'Malaria cummulative for 2012',
     'Malaria cummulative for 2013',
     'Malaria current week',
     'Malaria previous 52 weeks maximum ',
     'Malaria previous 52 weeks median ',
     'Measles Total cummulative for 2001',
     'Measles Total cummulative for 2002',
     'Meningococcal Disease cummulative for 2001',
     'Meningococcal Disease cummulative for 2002',
     'Meningococcal Disease cummulative for 2003',
     'Meningococcal Disease cummulative for 2004',
     'Meningococcal disease, All serogroups cummulative for 2004',
     'Meningococcal disease, All serogroups cummulative for 2005',
     'Meningococcal disease, Other serogroup cummulative for 2004',
     'Meningococcal disease, Other serogroup cummulative for 2005',
     'Meningococcal disease, Serogroup A, C, Y, and W-135 cummulative for 2004',
     'Meningococcal disease, Serogroup A, C, Y, and W-135 cummulative for 2005',
     'Meningococcal disease, Serogroup B cummulative for 2004',
     'Meningococcal disease, Serogroup B cummulative for 2005',
     'Meningococcal disease, Serogroup unknown cummulative for 2004',
     'Meningococcal disease, Serogroup unknown cummulative for 2005',
     'Meningococcal diseases, invasive \x86, All groups cummulative for 2009',
     'Meningococcal diseases, invasive \x86, All groups cummulative for 2010',
     'Meningococcal diseases, invasive \x86, All groups cummulative for 2011',
     'Meningococcal diseases, invasive \x86, All groups cummulative for 2012',
     'Meningococcal diseases, invasive \x86, All groups cummulative for 2013',
     'Meningococcal diseases, invasive \x86, All groups current week',
     'Meningococcal diseases, invasive \x86, All groups previous 52 weeks maximum ',
     'Meningococcal diseases, invasive \x86, All groups previous 52 weeks median ',
     'Meningococcal diseases, invasive \x86, all serogroups cummulative for 2006',
     'Meningococcal diseases, invasive \x86, all serogroups cummulative for 2007',
     'Meningococcal diseases, invasive \x86, all serogroups cummulative for 2008',
     'Meningococcal diseases, invasive \x86, all serogroups cummulative for 2009',
     'Meningococcal diseases, invasive \x86, all serogroups current week',
     'Meningococcal diseases, invasive \x86, all serogroups previous 52 weeks maximum ',
     'Meningococcal diseases, invasive \x86, all serogroups previous 52 weeks median ',
     'Meningococcal diseases, invasive, all serogroups cummulative for 2005',
     'Meningococcal diseases, invasive, all serogroups cummulative for 2006',
     'Meningococcal diseases, invasive, all serogroups current week',
     'Meningococcal diseases, invasive, all serogroups previous 52 weeks maximum ',
     'Meningococcal diseases, invasive, all serogroups previous 52 weeks median ',
     'Meningococcal diseases, invasive, serogroup unknown cummulative for 2005',
     'Meningococcal diseases, invasive, serogroup unknown cummulative for 2006',
     'Meningococcal diseases, invasive, serogroup unknown current week',
     'Meningococcal diseases, invasive, serogroup unknown previous 52 weeks maximum ',
     'Meningococcal diseases, invasive, serogroup unknown previous 52 weeks median ',
     'Mumps cummulative for 2001',
     'Mumps cummulative for 2002',
     'Mumps cummulative for 2010',
     'Mumps cummulative for 2011',
     'Mumps cummulative for 2012',
     'Mumps cummulative for 2013',
     'Mumps current week',
     'Mumps previous 52 weeks maximum ',
     'Mumps previous 52 weeks median ',
     'Pertussis cummulative for 2001',
     'Pertussis cummulative for 2002',
     'Pertussis cummulative for 2003',
     'Pertussis cummulative for 2004',
     'Pertussis cummulative for 2005',
     'Pertussis cummulative for 2006',
     'Pertussis cummulative for 2007',
     'Pertussis cummulative for 2008',
     'Pertussis cummulative for 2009',
     'Pertussis cummulative for 2010',
     'Pertussis cummulative for 2011',
     'Pertussis cummulative for 2012',
     'Pertussis cummulative for 2013',
     'Pertussis current week',
     'Pertussis previous 52 weeks maximum ',
     'Pertussis previous 52 weeks median ',
     'Rabies, Animal cummulative for 1999',
     'Rabies, Animal cummulative for 2000',
     'Rabies, Animal cummulative for 2001',
     'Rabies, Animal cummulative for 2002',
     'Rabies, Animal cummulative for 2003',
     'Rabies, Animal cummulative for 2004',
     'Rabies, animal cummulative for 2004',
     'Rabies, animal cummulative for 2005',
     'Rabies, animal cummulative for 2006',
     'Rabies, animal cummulative for 2007',
     'Rabies, animal cummulative for 2008',
     'Rabies, animal cummulative for 2009',
     'Rabies, animal cummulative for 2010',
     'Rabies, animal cummulative for 2011',
     'Rabies, animal cummulative for 2012',
     'Rabies, animal cummulative for 2013',
     'Rabies, animal current week',
     'Rabies, animal previous 52 weeks maximum ',
     'Rabies, animal previous 52 weeks median ',
     'Reporting Area',
     'Rocky Mountain Spotted Fever cummulative for 2001',
     'Rocky Mountain Spotted Fever cummulative for 2002',
     'Rocky Mountain Spotted Fever cummulative for 2003',
     'Rocky Mountain Spotted Fever cummulative for 2004',
     'Rocky Mountain Spotted Fever cummulative for 2005',
     'Rocky Mountain Spotted Fever cummulative for 2006',
     'Rocky Mountain Spotted Fever cummulative for 2007',
     'Rocky Mountain Spotted Fever cummulative for 2008',
     'Rocky Mountain Spotted Fever cummulative for 2009',
     'Rocky Mountain Spotted Fever current week',
     'Rocky Mountain Spotted Fever previous 52 weeks maximum ',
     'Rocky Mountain Spotted Fever previous 52 weeks median ',
     'Rubella Congenital cummulative for 2001',
     'Rubella Congenital cummulative for 2002',
     'Rubella cummulative for 2001',
     'Rubella cummulative for 2002',
     'Salmonellosis cummulative for 2001',
     'Salmonellosis cummulative for 2002',
     'Salmonellosis cummulative for 2003',
     'Salmonellosis cummulative for 2004',
     'Salmonellosis cummulative for 2005',
     'Salmonellosis cummulative for 2006',
     'Salmonellosis cummulative for 2007',
     'Salmonellosis cummulative for 2008',
     'Salmonellosis cummulative for 2009',
     'Salmonellosis cummulative for 2010',
     'Salmonellosis cummulative for 2011',
     'Salmonellosis cummulative for 2012',
     'Salmonellosis cummulative for 2013',
     'Salmonellosis current week',
     'Salmonellosis previous 52 weeks maximum ',
     'Salmonellosis previous 52 weeks median ',
     'Salmonellosis, NETSS cummulative for 1999',
     'Salmonellosis, NETSS cummulative for 2000',
     'Salmonellosis, NETSS cummulative for 2001',
     'Salmonellosis, PHLIS cummulative for 1999',
     'Salmonellosis, PHLIS cummulative for 2000',
     'Salmonellosis, PHLIS cummulative for 2001',
     'Shiga toxin-producing E. coli(STEC)\x86 cummulative for 2005',
     'Shiga toxin-producing E. coli(STEC)\x86 cummulative for 2006',
     'Shiga toxin-producing E. coli(STEC)\x86 cummulative for 2007',
     'Shiga toxin-producing E. coli(STEC)\x86 cummulative for 2008',
     'Shiga toxin-producing E. coli(STEC)\x86 cummulative for 2009',
     'Shiga toxin-producing E. coli(STEC)\x86 cummulative for 2010',
     'Shiga toxin-producing E. coli(STEC)\x86 cummulative for 2011',
     'Shiga toxin-producing E. coli(STEC)\x86 cummulative for 2012',
     'Shiga toxin-producing E. coli(STEC)\x86 cummulative for 2013',
     'Shiga toxin-producing E. coli(STEC)\x86 current week',
     'Shiga toxin-producing E. coli(STEC)\x86 previous 52 weeks maximum ',
     'Shiga toxin-producing E. coli(STEC)\x86 previous 52 weeks median ',
     'Shigellosis NETSS cummulative for 1999',
     'Shigellosis NETSS cummulative for 2000',
     'Shigellosis NETSS cummulative for 2001',
     'Shigellosis PHLIS cummulative for 1999',
     'Shigellosis PHLIS cummulative for 2000',
     'Shigellosis PHLIS cummulative for 2001',
     'Shigellosis cummulative for 2001',
     'Shigellosis cummulative for 2002',
     'Shigellosis cummulative for 2003',
     'Shigellosis cummulative for 2004',
     'Shigellosis cummulative for 2005',
     'Shigellosis cummulative for 2006',
     'Shigellosis cummulative for 2007',
     'Shigellosis cummulative for 2008',
     'Shigellosis cummulative for 2009',
     'Shigellosis cummulative for 2010',
     'Shigellosis cummulative for 2011',
     'Shigellosis cummulative for 2012',
     'Shigellosis cummulative for 2013',
     'Shigellosis current week',
     'Shigellosis previous 52 weeks maximum ',
     'Shigellosis previous 52 weeks median ',
     'Spotted Fever Rickettsiosis (including RMSF) \x86 Confirmed cummulative for 2009',
     'Spotted Fever Rickettsiosis (including RMSF) \x86 Confirmed cummulative for 2010',
     'Spotted Fever Rickettsiosis (including RMSF) \x86 Confirmed cummulative for 2011',
     'Spotted Fever Rickettsiosis (including RMSF) \x86 Confirmed cummulative for 2012',
     'Spotted Fever Rickettsiosis (including RMSF) \x86 Confirmed cummulative for 2013',
     'Spotted Fever Rickettsiosis (including RMSF) \x86 Confirmed current week',
     'Spotted Fever Rickettsiosis (including RMSF) \x86 Confirmed previous 52 weeks maximum ',
     'Spotted Fever Rickettsiosis (including RMSF) \x86 Confirmed previous 52 weeks median ',
     'Spotted Fever Rickettsiosis (including RMSF) \x86 Probable cummulative for 2009',
     'Spotted Fever Rickettsiosis (including RMSF) \x86 Probable cummulative for 2010',
     'Spotted Fever Rickettsiosis (including RMSF) \x86 Probable cummulative for 2011',
     'Spotted Fever Rickettsiosis (including RMSF) \x86 Probable cummulative for 2012',
     'Spotted Fever Rickettsiosis (including RMSF) \x86 Probable cummulative for 2013',
     'Spotted Fever Rickettsiosis (including RMSF) \x86 Probable current week',
     'Spotted Fever Rickettsiosis (including RMSF) \x86 Probable previous 52 weeks maximum ',
     'Spotted Fever Rickettsiosis (including RMSF) \x86 Probable previous 52 weeks median ',
     'Streptococcal Disease, Invasive, Group A cummulative for 2001',
     'Streptococcal Disease, Invasive, Group A cummulative for 2002',
     'Streptococcal Disease, Invasive, Group A cummulative for 2003',
     'Streptococcal Disease, Invasive, Group A cummulative for 2004',
     'Streptococcal Disease, Invasive, Group A cummulative for 2005',
     'Streptococcal disease, invasive, group A cummulative for 2005',
     'Streptococcal disease, invasive, group A cummulative for 2006',
     'Streptococcal disease, invasive, group A cummulative for 2007',
     'Streptococcal disease, invasive, group A cummulative for 2008',
     'Streptococcal disease, invasive, group A cummulative for 2009',
     'Streptococcal disease, invasive, group A current week',
     'Streptococcal disease, invasive, group A previous 52 weeks maximum ',
     'Streptococcal disease, invasive, group A previous 52 weeks median ',
     'Streptococcus pneumoniae, Drug Resistant, Invasive cummulative for 2001',
     'Streptococcus pneumoniae, Drug Resistant, Invasive cummulative for 2002',
     'Streptococcus pneumoniae, Drug Resistant, Invasive, All Ages cummulative for 2002',
     'Streptococcus pneumoniae, Drug Resistant, Invasive, All Ages cummulative for 2003',
     'Streptococcus pneumoniae, Drug Resistant, Invasive, All Ages cummulative for 2004',
     'Streptococcus pneumoniae, Invasive Disease, Age < 5 Years cummulative for 2001',
     'Streptococcus pneumoniae, Invasive Disease, Age < 5 Years cummulative for 2002',
     'Streptococcus pneumoniae, Invasive Disease, Age < 5 Years cummulative for 2003',
     'Streptococcus pneumoniae, Invasive Disease, Age < 5 Years cummulative for 2004',
     'Streptococcus pneumoniae, Invasive, Age < 5 Years cummulative for 2004',
     'Streptococcus pneumoniae, Invasive, Age < 5 Years cummulative for 2005',
     'Streptococcus pneumoniae, Invasive, Drug Resistant, all ages cummulative for 2004',
     'Streptococcus pneumoniae, Invasive, Drug Resistant, all ages cummulative for 2005',
     'Streptococcus pneumoniae, invasive disease \x86, Age <5 years cummulative for 2006',
     'Streptococcus pneumoniae, invasive disease \x86, Age <5 years cummulative for 2007',
     'Streptococcus pneumoniae, invasive disease \x86, Age <5 years current week',
     'Streptococcus pneumoniae, invasive disease \x86, Age <5 years previous 52 weeks maximum ',
     'Streptococcus pneumoniae, invasive disease \x86, Age <5 years previous 52 weeks median ',
     'Streptococcus pneumoniae, invasive disease \x86, age <5 years cummulative for 2009',
     'Streptococcus pneumoniae, invasive disease \x86, age <5 years cummulative for 2010',
     'Streptococcus pneumoniae, invasive disease \x86, age <5 years cummulative for 2011',
     'Streptococcus pneumoniae, invasive disease \x86, age <5 years cummulative for 2012',
     'Streptococcus pneumoniae, invasive disease \x86, age <5 years cummulative for 2013',
     'Streptococcus pneumoniae, invasive disease \x86, age <5 years current week',
     'Streptococcus pneumoniae, invasive disease \x86, age <5 years previous 52 weeks maximum ',
     'Streptococcus pneumoniae, invasive disease \x86, age <5 years previous 52 weeks median ',
     'Streptococcus pneumoniae, invasive disease \x86, all ages cummulative for 2009',
     'Streptococcus pneumoniae, invasive disease \x86, all ages cummulative for 2010',
     'Streptococcus pneumoniae, invasive disease \x86, all ages cummulative for 2011',
     'Streptococcus pneumoniae, invasive disease \x86, all ages cummulative for 2012',
     'Streptococcus pneumoniae, invasive disease \x86, all ages cummulative for 2013',
     'Streptococcus pneumoniae, invasive disease \x86, all ages current week',
     'Streptococcus pneumoniae, invasive disease \x86, all ages previous 52 weeks maximum ',
     'Streptococcus pneumoniae, invasive disease \x86, all ages previous 52 weeks median ',
     'Streptococcus pneumoniae, invasive disease, drug resistant \x86, age <5 years cummulative for 2006',
     'Streptococcus pneumoniae, invasive disease, drug resistant \x86, age <5 years cummulative for 2007',
     'Streptococcus pneumoniae, invasive disease, drug resistant \x86, age <5 years cummulative for 2008',
     'Streptococcus pneumoniae, invasive disease, drug resistant \x86, age <5 years cummulative for 2009',
     'Streptococcus pneumoniae, invasive disease, drug resistant \x86, age <5 years current week',
     'Streptococcus pneumoniae, invasive disease, drug resistant \x86, age <5 years previous 52 weeks maximum ',
     'Streptococcus pneumoniae, invasive disease, drug resistant \x86, age <5 years previous 52 weeks median ',
     'Streptococcus pneumoniae, invasive disease, drug resistant \x86, all ages cummulative for 2006',
     'Streptococcus pneumoniae, invasive disease, drug resistant \x86, all ages cummulative for 2007',
     'Streptococcus pneumoniae, invasive disease, drug resistant \x86, all ages cummulative for 2008',
     'Streptococcus pneumoniae, invasive disease, drug resistant \x86, all ages cummulative for 2009',
     'Streptococcus pneumoniae, invasive disease, drug resistant \x86, all ages current week',
     'Streptococcus pneumoniae, invasive disease, drug resistant \x86, all ages previous 52 weeks maximum ',
     'Streptococcus pneumoniae, invasive disease, drug resistant \x86, all ages previous 52 weeks median ',
     'Streptococcus pneumoniae, invasive disease, drug resistant, all ages cummulative for 2005',
     'Streptococcus pneumoniae, invasive disease, drug resistant, all ages cummulative for 2006',
     'Streptococcus pneumoniae, invasive disease, drug resistant, all ages current week',
     'Streptococcus pneumoniae, invasive disease, drug resistant, all ages previous 52 weeks maximum ',
     'Streptococcus pneumoniae, invasive disease, drug resistant, all ages previous 52 weeks median ',
     'Streptococcus pneumoniae, invasive disease, nondrug resistant \x86, Age <5 years cummulative for 2006',
     'Streptococcus pneumoniae, invasive disease, nondrug resistant \x86, Age <5 years cummulative for 2007',
     'Streptococcus pneumoniae, invasive disease, nondrug resistant \x86, Age <5 years cummulative for 2008',
     'Streptococcus pneumoniae, invasive disease, nondrug resistant \x86, Age <5 years cummulative for 2009',
     'Streptococcus pneumoniae, invasive disease, nondrug resistant \x86, Age <5 years current week',
     'Streptococcus pneumoniae, invasive disease, nondrug resistant \x86, Age <5 years previous 52 weeks maximum ',
     'Streptococcus pneumoniae, invasive disease, nondrug resistant \x86, Age <5 years previous 52 weeks median ',
     'Syphilis (Congenital) cummulative for 2001',
     'Syphilis (Congenital) cummulative for 2002',
     'Syphilis (Congenital) cummulative for 2003',
     'Syphilis (Congenital) cummulative for 2004',
     'Syphilis (Congenital) cummulative for 2005',
     'Syphilis (Primary and Secondary) cummulative for 1999',
     'Syphilis (Primary and Secondary) cummulative for 2000',
     'Syphilis (Primary and Secondary) cummulative for 2001',
     'Syphilis (Primary and Secondary) cummulative for 2002',
     'Syphilis (Primary and Secondary) cummulative for 2003',
     'Syphilis (Primary and Secondary) cummulative for 2004',
     'Syphilis (Primary and Secondary) cummulative for 2005',
     'Syphillis, primary & secondary cummulative for 2005',
     'Syphillis, primary & secondary cummulative for 2006',
     'Syphillis, primary & secondary cummulative for 2007',
     'Syphillis, primary & secondary cummulative for 2008',
     'Syphillis, primary & secondary cummulative for 2009',
     'Syphillis, primary & secondary cummulative for 2010',
     'Syphillis, primary & secondary cummulative for 2011',
     'Syphillis, primary & secondary cummulative for 2012',
     'Syphillis, primary & secondary cummulative for 2013',
     'Syphillis, primary & secondary current week',
     'Syphillis, primary & secondary previous 52 weeks maximum ',
     'Syphillis, primary & secondary previous 52 weeks median ',
     'Tuberculosis cummulative for 1999',
     'Tuberculosis cummulative for 2000',
     'Tuberculosis cummulative for 2001',
     'Tuberculosis cummulative for 2002',
     'Tuberculosis cummulative for 2003',
     'Tuberculosis cummulative for 2004',
     'Tuberculosis cummulative for 2005',
     'Typhoid Fever cummulative for 2001',
     'Typhoid Fever cummulative for 2002',
     'Typhoid Fever cummulative for 2003',
     'Typhoid Fever cummulative for 2004',
     'Typhoid Fever cummulative for 2005',
     'Varicella (Chicken Pox) cummulative for 2002',
     'Varicella (Chicken Pox) cummulative for 2003',
     'Varicella (Chicken Pox) cummulative for 2004',
     'Varicella (Chicken Pox) cummulative for 2005',
     'Varicella (chickenpox) cummulative for 2005',
     'Varicella (chickenpox) cummulative for 2006',
     'Varicella (chickenpox) cummulative for 2007',
     'Varicella (chickenpox) cummulative for 2008',
     'Varicella (chickenpox) cummulative for 2009',
     'Varicella (chickenpox) cummulative for 2010',
     'Varicella (chickenpox) cummulative for 2011',
     'Varicella (chickenpox) cummulative for 2012',
     'Varicella (chickenpox) cummulative for 2013',
     'Varicella (chickenpox) current week',
     'Varicella (chickenpox) previous 52 weeks maximum ',
     'Varicella (chickenpox) previous 52 weeks median ',
     'West Nile virus disease \x86 Neuroinvasive cummulative for 2005',
     'West Nile virus disease \x86 Neuroinvasive cummulative for 2006',
     'West Nile virus disease \x86 Neuroinvasive cummulative for 2007',
     'West Nile virus disease \x86 Neuroinvasive cummulative for 2008',
     'West Nile virus disease \x86 Neuroinvasive cummulative for 2009',
     'West Nile virus disease \x86 Neuroinvasive cummulative for 2010',
     'West Nile virus disease \x86 Neuroinvasive cummulative for 2011',
     'West Nile virus disease \x86 Neuroinvasive cummulative for 2012',
     'West Nile virus disease \x86 Neuroinvasive cummulative for 2013',
     'West Nile virus disease \x86 Neuroinvasive current week',
     'West Nile virus disease \x86 Neuroinvasive previous 52 weeks maximum ',
     'West Nile virus disease \x86 Neuroinvasive previous 52 weeks median ',
     'West Nile virus disease \x86 Non-neuroinvasive cummulative for 2005',
     'West Nile virus disease \x86 Non-neuroinvasive cummulative for 2006',
     'West Nile virus disease \x86 Non-neuroinvasive current week',
     'West Nile virus disease \x86 Non-neuroinvasive previous 52 weeks maximum ',
     'West Nile virus disease \x86 Non-neuroinvasive previous 52 weeks median ',
     'West Nile virus disease \x86 Non-neuroinvasive \xa7 cummulative for 2006',
     'West Nile virus disease \x86 Non-neuroinvasive \xa7 cummulative for 2007',
     'West Nile virus disease \x86 Non-neuroinvasive \xa7 cummulative for 2008',
     'West Nile virus disease \x86 Non-neuroinvasive \xa7 cummulative for 2009',
     'West Nile virus disease \x86 Non-neuroinvasive \xa7 cummulative for 2010',
     'West Nile virus disease \x86 Non-neuroinvasive \xa7 cummulative for 2011',
     'West Nile virus disease \x86 Non-neuroinvasive \xa7 cummulative for 2012',
     'West Nile virus disease \x86 Non-neuroinvasive \xa7 cummulative for 2013',
     'West Nile virus disease \x86 Non-neuroinvasive \xa7 current week',
     'West Nile virus disease \x86 Non-neuroinvasive \xa7 previous 52 weeks maximum ',
     'West Nile virus disease \x86 Non-neuroinvasive \xa7 previous 52 weeks median ',
     'West Nile virus disease \xa7 Neuroinvasive cummulative for 2004',
     'West Nile virus disease \xa7 Neuroinvasive cummulative for 2005',
     'West Nile virus disease \xa7 Non-neuroinvasive \x86 cummulative for 2005']